version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - "./public:/app/public"
      - "./src:/app/src"
      - "/app/node_modules"
